apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: cd-pipeline
spec:
  params:
    - name: app-name
      type: string
    - name: git-url
      type: string
    - name: build-image
      type: string

  workspaces:
    - name: output

  tasks:

    - name: cleanup
      taskRef:
        name: cleanup
      workspaces:
        - name: source
          workspace: output

    - name: clone
      runAfter:
        - cleanup
      taskRef:
        name: git-clone
      params:
        - name: url
          value: $(params.git-url)
      workspaces:
        - name: output
          workspace: output

    - name: lint
      runAfter:
        - git
      taskRef:
        name: flake8
      workspaces:
        - name: source
          workspace: output

    - name: test
      taskRef:
        name: nose
      workspaces:
        - name: source
          workspace: output

    - name: build
      taskRef:
        name: buildah
      params:
        - name: IMAGE
          value: $(params.build-image)
      workspaces:
        - name: source
          workspace: output

    - name: deploy
      taskRef:
        name: openshift-client
      params:
        - name: SCRIPT
          value: |
            oc create deployment $(params.app-name) \
            --image=$(params.build-image) \
            --dry-run=client -o yaml | oc apply -f -